// This file is automatically generated. Do not edit it directly.
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface NewUserNotification {
  email: string;
  name?: string;
  role?: string;
}

serve(async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const payload: NewUserNotification = await req.json();

    const { email, name, role } = payload;

    const html = `
      <h1>New User Registration</h1>
      <p>A new user has signed up.</p>
      <ul>
        <li><strong>Name:</strong> ${name || "N/A"}</li>
        <li><strong>Email:</strong> ${email}</li>
        <li><strong>Role:</strong> ${role || "N/A"}</li>
      </ul>
      <p>Review and approve the user in the admin dashboard.</p>
    `;

    const toEmail = "fwdfwdit@gmail.com"; // Admin email to notify

    const emailResponse = await resend.emails.send({
      from: "RoadSync Board <onboarding@resend.dev>",
      to: [toEmail],
      subject: "New User Registration",
      html,
    });

    console.log("Admin notification sent:", emailResponse);

    return new Response(JSON.stringify({ ok: true }), {
      status: 200,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  } catch (error: any) {
    console.error("Error in notify-admin function:", error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  }
});
