// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbyimtzjvwqcsnuwjzhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhieWltdHpqdndxY3NudXdqemh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NzA0MDMsImV4cCI6MjA3MjM0NjQwM30.5PLfsx_kM8UBKwO2Fprt9xQmATu3zgY9XZapyrG9fe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});